# Feature Prep Tu Cache Log

Notebook nay dung cache `user_log_agg_v1_*.parquet` de bo qua buoc aggregate `user_logs*.7z` rat ton thoi gian.

Muc tieu:
- giu nguyen logic nghiep vu cua `feature_prep.ipynb` cho phan label va feature layer;
- tai truc tiep cache log theo thang;
- export feature store ra mot thu muc rieng de tranh ghi de;
- bao cao lech voi `sample_submission_v2.csv` thay vi fail hard o cuoi notebook.

In [1]:
from pathlib import Path
import sys
import pandas as pd

CANDIDATE_NOTEBOOK_DIRS = [
    Path.cwd(),
    Path.cwd() / 'project-realtime-bi' / 'notebooks',
]

for candidate in CANDIDATE_NOTEBOOK_DIRS:
    helper_path = candidate / 'feature_prep_from_cache_lib.py'
    if helper_path.exists():
        sys.path.insert(0, str(candidate))
        NOTEBOOK_DIR = candidate
        break
else:
    raise FileNotFoundError('Khong tim thay feature_prep_from_cache_lib.py')

from feature_prep_from_cache_lib import run_feature_prep_from_cache

print(f'NOTEBOOK_DIR = {NOTEBOOK_DIR}')

NOTEBOOK_DIR = /Users/anhoaithai/Documents/AHT/2. AREAS/UEH/Kì 6/Hệ hỗ trợ quản trị thông minh/Project/project-realtime-bi/notebooks

In [3]:
OUTPUT_SUBDIR = 'feature_store_from_cache'
STRICT_TEST_COHORT_MATCH = False

result = run_feature_prep_from_cache(
    output_subdir=OUTPUT_SUBDIR,
    strict_test_cohort_match=STRICT_TEST_COHORT_MATCH,
)

summary_df = pd.DataFrame([result['summary']])
coverage_df = result['cache_coverage_df']
submission_report = result['submission_report']

display(summary_df)
display(coverage_df)
if submission_report is not None:
    display(pd.DataFrame([submission_report]))

PROJECT_DIR = /Users/anhoaithai/Documents/AHT/2. AREAS/UEH/Kì 6/Hệ hỗ trợ quản trị thông minh/Project/project-realtime-bi
DATA_DIR = /Users/anhoaithai/Documents/AHT/2. AREAS/UEH/Kì 6/Hệ hỗ trợ quản trị thông minh/Project/project-realtime-bi/data/raw
ARTIFACT_ROOT = /Users/anhoaithai/Documents/AHT/2. AREAS/UEH/Kì 6/Hệ hỗ trợ quản trị thông minh/Project/project-realtime-bi/data/artifacts
LOG_AGG_CACHE_DIR = /Users/anhoaithai/Documents/AHT/2. AREAS/UEH/Kì 6/Hệ hỗ trợ quản trị thông minh/Project/project-realtime-bi/data/artifacts/feature_store/log_agg_cache
FEATURE_STORE_DIR = /Users/anhoaithai/Documents/AHT/2. AREAS/UEH/Kì 6/Hệ hỗ trợ quản trị thông minh/Project/project-realtime-bi/data/artifacts/feature_store_from_cache
Using transaction files: ['transactions_v2.csv']
Warning: missing transaction sources: ['transactions.csv']

Building labels:   0%|          | 0/1197050 [00:00<?, ?it/s]

   log_month  required_msnos  cached_rows  usable_rows  \
0     201612               1       673732            0
1     201701               1       680937            0
2     201702               1       682933            0
3     201703          906743       699066       699066

   missing_required_msnos  unexpected_cached_msnos  \
0                       1                   673732
1                       1                   680937
2                       1                   682933
3                  207677                        0

                                          cache_path
0  /Users/anhoaithai/Documents/AHT/2. AREAS/UEH/K...
1  /Users/anhoaithai/Documents/AHT/2. AREAS/UEH/K...
2  /Users/anhoaithai/Documents/AHT/2. AREAS/UEH/K...
3  /Users/anhoaithai/Documents/AHT/2. AREAS/UEH/K...
201701 raw feature frame: (1, 47)
201702 raw feature frame: (1, 47)
201703 raw feature frame: (1, 47)
201704 raw feature frame: (906743, 47)
201701 enriched frame: (1, 124)
201702 enriched frame: (1, 124)
201703 enriched frame: (1, 124)
201704 enriched frame: (906743, 124)
{
  "project_dir": "/Users/anhoaithai/Documents/AHT/2. AREAS/UEH/Kì 6/Hệ hỗ trợ quản trị thông minh/Project/project-realtime-bi",
  "data_dir": "/Users/anhoaithai/Documents/AHT/2. AREAS/UEH/Kì 6/Hệ hỗ trợ quản trị thông minh/Project/project-realtime-bi/data/raw",
  "artifact_root": "/Users/anhoaithai/Documents/AHT/2. AREAS/UEH/Kì 6/Hệ hỗ trợ quản trị thông minh/Project/project-realtime-bi/data/artifacts",
  "log_cache_dir": "/Users/anhoaithai/Documents/AHT/2. AREAS/UEH/Kì 6/Hệ hỗ trợ quản trị thông minh/Project/project-realtime-bi/data/artifacts/feature_store/log_agg_cache",
  "feature_store_dir": "/Users/anhoaithai/Documents/AHT/2. AREAS/UEH/Kì 6/Hệ hỗ trợ quản trị thông minh/Project/project-realtime-bi/data/artifacts/feature_store_from_cache",
  "train_rows": 3,
  "test_cohort_rows": 906743,
  "bi_snapshot_rows": 906746,
  "model_feature_count": 110
}

,project_dir,data_dir,artifact_root,log_cache_dir,feature_store_dir,train_rows,test_cohort_rows,bi_snapshot_rows,model_feature_count
0,/Users/anhoaithai/Documents/AHT/2. AREAS/UEH/K...,/Users/anhoaithai/Documents/AHT/2. AREAS/UEH/K...,/Users/anhoaithai/Documents/AHT/2. AREAS/UEH/K...,/Users/anhoaithai/Documents/AHT/2. AREAS/UEH/K...,/Users/anhoaithai/Documents/AHT/2. AREAS/UEH/K...,3,906743,906746,110

,log_month,required_msnos,cached_rows,usable_rows,missing_required_msnos,unexpected_cached_msnos,cache_path
0,201612,1,673732,0,1,673732,/Users/anhoaithai/Documents/AHT/2. AREAS/UEH/K...
1,201701,1,680937,0,1,680937,/Users/anhoaithai/Documents/AHT/2. AREAS/UEH/K...
2,201702,1,682933,0,1,682933,/Users/anhoaithai/Documents/AHT/2. AREAS/UEH/K...
3,201703,906743,699066,699066,207677,0,/Users/anhoaithai/Documents/AHT/2. AREAS/UEH/K...

In [4]:
preview_cols = [
    'msno',
    'target_month',
    'is_churn',
    'expected_renewal_amount',
    'skip_ratio',
    'discovery_ratio',
    'price_segment',
    'loyalty_segment',
    'active_segment',
    'bi_segment_name',
]
display(result['bi_snapshot_df'][preview_cols].head())

,msno,target_month,is_churn,expected_renewal_amount,skip_ratio,discovery_ratio,price_segment,loyalty_segment,active_segment,bi_segment_name
0,VJx7ZXB+BP/17UpJTYyAsv7ItjWWaRrtY/Zg0+VE=,201701,0,99.0,0.000000,0.000000,Deal Hunter < 4.5,Unknown,Unknown,Unknown | Pay_Auto-Renew | Deal Hunter < 4.5 |...
1,VJx7ZXB+BP/17UpJTYyAsv7ItjWWaRrtY/Zg0+VE=,201702,0,99.0,0.000000,0.000000,Deal Hunter < 4.5,Unknown,Unknown,Unknown | Pay_Auto-Renew | Deal Hunter < 4.5 |...
2,VJx7ZXB+BP/17UpJTYyAsv7ItjWWaRrtY/Zg0+VE=,201703,0,99.0,0.000000,0.000000,Deal Hunter < 4.5,Unknown,Unknown,Unknown | Pay_Auto-Renew | Deal Hunter < 4.5 |...
3,+++hVY1rZox/33YtvDgmKA2Frg/2qhkz12B9ylCvh8o=,201704,1,99.0,0.326905,0.812672,Deal Hunter < 4.5,Loyal >= 365d,Heavy > 15 logs,Loyal >= 365d | Pay_Auto-Renew | Deal Hunter <...
4,+++snpr7pmobhLKUgSHTv/mpkqgBT0tQJ0zQj6qKrqc=,201704,1,149.0,0.484536,0.853608,Standard 4.5-6.5,Loyal >= 365d,Heavy > 15 logs,Loyal >= 365d | Pay_Auto-Renew | Standard 4.5-...